#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Playground.Resource", IsApplication=true)]

namespace Playground
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040002
			public const int font_size_large = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int font_size_medium = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int font_size_small = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int esri = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int GoToControl = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int GoToMap = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int GoToMapFrag = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int GoToMapN = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int MapFragmentContainer = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int MapView = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int MapViewFrag = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int MemUsage = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int gcx = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Control = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Map = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MapFrag = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MapFragContainer = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
